name: ci

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:

  lint:
    name: Static Code Analysis
    runs-on: ubuntu-22.04
    permissions: read-all
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2.0.2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  test:
    name: Testing
    needs: lint
    runs-on: ubuntu-22.04
    steps:
      - name: Test
        run: echo "executing unit tests . . ."

  build:
    name: build docker image
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: build image
        run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/ci-final-frontend:latest
      - name: delete built image
        run: docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/ci-final-frontend:latest